"""
Modelos de Zentra+.

Todo lo que sea una tabla se reexporta aqui: es lo que lee `alembic/env.py` para
detectar el esquema y lo que leen los tests para crear las tablas. Un modelo que
no aparezca en este archivo no existe para las migraciones.
"""

from app.models.auth import RefreshToken
from app.models.base import ConSucursal, IdUUID, Timestamps, ahora_utc
from app.models.branch import (
    Branch,
    BranchCounter,
    BranchCreate,
    BranchPublic,
    BranchUpdate,
)
from app.models.cash import (
    ESTADOS_DE_TURNO,
    AbrirTurno,
    ArqueoPublic,
    CerrarTurno,
    CobroNuevo,
    EstadoDeCobro,
    Payment,
    PaymentPublic,
    PropinaNueva,
    Shift,
    ShiftPublic,
)
from app.models.catalog import (
    ESTACIONES,
    Category,
    CategoryCreate,
    CategoryPublic,
    CategoryUpdate,
    ModifierGroup,
    ModifierGroupCreate,
    ModifierGroupPublic,
    ModifierOption,
    ModifierOptionPublic,
    Product,
    ProductBranch,
    ProductBranchUpdate,
    ProductCreate,
    ProductModifierGroup,
    ProductPublic,
    ProductUpdate,
)
from app.models.floor import (
    ESTADOS_DE_MESA,
    FORMAS_DE_MESA,
    RestaurantTable,
    Sector,
    SectorCreate,
    SectorPublic,
    SectorUpdate,
    TableCreate,
    TableLayoutItem,
    TableLayoutUpdate,
    TablePublic,
    TableStatusUpdate,
    TableUpdate,
)
from app.models.order import (
    ORIGENES,
    ORIGENES_PEDIBLES,
    CambioDeEstado,
    LineaAnadida,
    LineaNueva,
    OrdenNueva,
    Order,
    OrderItem,
    OrderItemPublic,
    OrderPublic,
    OrderStatusHistory,
)
from app.models.role import (
    Permission,
    PermissionPublic,
    Role,
    RolePermission,
    RolePublic,
)
from app.models.settings import (
    BusinessConfig,
    BusinessConfigPublic,
    BusinessConfigUpdate,
)
from app.models.user import (
    LoginPorCorreo,
    LoginPorPin,
    User,
    UserBranch,
    UserOperativo,
    UserPublic,
)

__all__ = [
    "ESTACIONES",
    "ESTADOS_DE_TURNO",
    "ORIGENES",
    "ORIGENES_PEDIBLES",
    "ESTADOS_DE_MESA",
    "FORMAS_DE_MESA",
    "Branch",
    "BranchCounter",
    "BranchCreate",
    "BranchPublic",
    "BranchUpdate",
    "BusinessConfig",
    "BusinessConfigPublic",
    "BusinessConfigUpdate",
    "Category",
    "CategoryCreate",
    "CategoryPublic",
    "CategoryUpdate",
    "ConSucursal",
    "IdUUID",
    "LoginPorCorreo",
    "LoginPorPin",
    "ModifierGroup",
    "ModifierGroupCreate",
    "ModifierGroupPublic",
    "AbrirTurno",
    "ArqueoPublic",
    "CambioDeEstado",
    "CerrarTurno",
    "CobroNuevo",
    "EstadoDeCobro",
    "LineaAnadida",
    "LineaNueva",
    "ModifierOption",
    "ModifierOptionPublic",
    "OrdenNueva",
    "Order",
    "OrderItem",
    "OrderItemPublic",
    "OrderPublic",
    "OrderStatusHistory",
    "Payment",
    "PaymentPublic",
    "PropinaNueva",
    "Permission",
    "PermissionPublic",
    "Product",
    "ProductBranch",
    "ProductBranchUpdate",
    "ProductCreate",
    "ProductModifierGroup",
    "ProductPublic",
    "ProductUpdate",
    "RefreshToken",
    "RestaurantTable",
    "Role",
    "RolePermission",
    "RolePublic",
    "Sector",
    "Shift",
    "ShiftPublic",
    "SectorCreate",
    "SectorPublic",
    "SectorUpdate",
    "TableCreate",
    "TableLayoutItem",
    "TableLayoutUpdate",
    "TablePublic",
    "TableStatusUpdate",
    "TableUpdate",
    "Timestamps",
    "User",
    "UserBranch",
    "UserOperativo",
    "UserPublic",
    "ahora_utc",
]
